#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Marcello Almeida'
        hostname: ubuntu-Soares
        username: Marcello
        password: '$y$j9T$1L72C2ujYqmvBU23TL6f91$CugtVVodol7bo8X5KAVD2yiEpgwJ2IWIDCirAuHsMh8'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - libreoffice
        - gimp
        - git
        - wget
    snaps:
        - name: spotify
          channel: stable
          classic: false
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot

